name: CI
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test-solana-programs:
    name: Build and Test Solana Programs
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          cache-all-crates: true

      - name: Install Solana CLI 2.1.21
        shell: bash
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.21/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Show versions
        run: |
          rustc --version
          cargo --version
          solana --version

      - name: Build
        run: cd solana && cargo-build-sbf

      - name: Test
        run: cd solana && cargo test
