name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test-solana-program:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install Solana CLI 2.1.21
        shell: bash
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.21/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Show versions
        run: |
          rustc --version
          cargo --version
          solana --version

      - name: Build
        run: cd solana && cargo-build-sbf

      - name: Test
        run: cd solana && cargo test
