name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test-solana-program:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Show versions
        run: |
          rustc --version
          cargo --version

      - name: Build
        run: cargo-build-sbf

      - name: Test
        run: cargo test
